# Generated by Django 6.1 on 2026-08-27 19:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaborationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
